apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: httpdump-external
  annotations:
    kubernetes.io/ingress.class: ingressclass
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /httpdump/(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: httpdump
              servicePort: 8080