apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpdump-internal
  annotations:
    kubernetes.io/ingress.class: myingressclass
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /helloworld/(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: helloworld-svc
              servicePort: 8080